fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive.git"
      ref:  "v1.3.0"
  symlinks:
    aerospike: "#{source_dir}"
